# Profile to proxy requests to the deployed IAM and Organization services.
services.iam.url=https://meditrack-iam-gmh0b2eshgcpbmhw.eastus-01.azurewebsites.net
services.organization.url=https://meditrack-organization.duckdns.org
